export const config = {
  BCRYPT_ROUNDS: 12,
  PAGINATION_DEFAULT_LIMIT: 50,
  PAGINATION_MAX_LIMIT: 100,
  CARD_MOVE_BATCH_SIZE: 50,
  R2_SIGNED_URL_TTL: 900,
  LIVEKIT_TOKEN_TTL: 21600,
  RATE_LIMIT_WINDOW_MS: 60_000,
  RATE_LIMIT_MAX: 100,
  RATE_LIMIT_UPLOAD_MAX: 10,
  RATE_LIMIT_VOICE_TOKEN_MAX: 5,
};
